### PR TITLE
Bug fix for Storage

### LINKED ISSUE #156: [PE-D][Tester B] [TP] Duplicates in Data File not identified
When there are duplicates with the same indentation, the program would automatically delete the duplicates leaving one behind. However, when there are indentation differences in the data file, the duplicates would not be identified, leaving all in the program. When loading the data, you could trim the parameters to remove the different indentations, making it easier to compare for duplicates.

Indentation differences:

Output in program: 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: glenda-1506/ped#4

### LINKED ISSUE #160: [PE-D][Tester C] Tampering with Save files allow for inconsistent scores
1. add student Alice with matric. number A1234567W

2. add component Quiz 1 with any weightage and max. score of 100

3. add grade to Alice for Quiz 1 with score 60.

4. Exit app.

5. Go into studentlist.txt and change Alice's percentage to 100.0.

6. Restart app.

App will show Alice's percentage score as 100 when list_student is entered, but as 60% when calling list_grade.

Perhaps checks could be done to ensure consistency in data across all storage files?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: limkongkiat/ped#4

### LINKED ISSUE #161: [PE-D][Tester B] [TP] Percentage score in Data File more than 100 or negative
Users are able to change percentage score in the studentlist.txt file. However, it does not catch when there are invalid numbers, such as negative numbers or more than 100. When loading the data files, you could do checks for the validity of the numbers in the data files, flagging out the invalid values.

Data file:

Output in program:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: glenda-1506/ped#5

### LINKED ISSUE #167: [PE-D][Tester C] Duplicate grades can be added for a single student and component through storage text file.
1. Add new student Alice with matric number A1234567W

2. Add component Quiz 1 with max score 100 and assign Alice a grade of 60.

3. Exit app

4. To gradelist.txt, add: `Quiz 1 | A1234567W | 50.0`

5. Repoen app

App will show duplicate scores for Alice's Quiz 1. Furthermore, grades across list_student and list_grade are inconsistent.

Perhaps more could be done to prevent this?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: limkongkiat/ped#5

### LINKED ISSUE #179: [PE-D][Tester C] App does not handle file corruption as specified in the DG
DG states that TutorLink should detect the corrupted or invalid data, display them to the user as entries to be discarded, and only load valid data entries.

Steps to create bug:

1. add_student i/A1234567W n/Alice
2. exit app
3. go to studentlist.txt and shorten Alice's matriculation number to A4567W.
4. Reopen app.
5. list_student

App does not detect the invalid matriculation number, but loads Alice's name as if the entry was valid.

Furthermore, when trying to add grade to Alice, the app registers A4567W as an invalid matriculation number and  disallows a grade to be added for Alice.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: limkongkiat/ped#8

### LINKED ISSUE #189: [PE-D][Tester C] Editing studentlist.txt directly allows students to be recorded with percentage scores above 100.
Steps:
1. add_student i/A1234567W n/Alice
2. exit app
3. Edit studentlist.txt, changing Alice's percentage score to 102.
4. Reopen app

App shows Alice's percentage score as 102 when percentage scores should not exceed 100. This is contrary to the Developer Guide's claim that the app will discard invalid data entry detected in the storage file.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: limkongkiat/ped#11

### LINKED ISSUE #191: [PE-D][Tester C] Editing componentlist.txt can allow for total weightage of all components to exceed 100%
Steps:
1. add_component c/Quiz 1 w/50 m/50
2. add_component c/Quiz 2 w/50 m/50
3. Exit app
4. Go to componentlist.txt and edit weightage of Quiz 1 to 60
5. Reopen app

list_component shows total weightage to be 110%. It does not detect the invalid data entry as claimed by the DG.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: limkongkiat/ped#12

### PR DESCRIPTION
**Pull request by jinzihan2002**
Fixes #160
Fixes #161 
Fixes #189 
- done by not storing gpa in studentlist.txt, instead calculating gpa once all data has been loaded

Fixes #156 
Fixes #167 
Fixes #179 
Fixes #191

### CODE REVIEW

File: src/main/java/tutorlink/storage/StudentStorage.java [hunk 1]
```diff
@@ -39,23 +42,26 @@ private Student getStudentFromFileLine(String fileLine, ArrayList<Student> stude
...
         try {
-            String matricNumber = stringParts[0];
-            String name = stringParts[1];
-            String gpaString = stringParts[2];
-            double gpa = Double.parseDouble(gpaString);
-            Student newStudent = new Student(matricNumber, name, gpa);
+            String matricNumber = stringParts[0].strip().toUpperCase();
+            String name = stringParts[1].strip();
+            Pattern pattern = Pattern.compile(Commons.MATRIC_NUMBER_REGEX);
+            Matcher matcher = pattern.matcher(matricNumber);
```
Comment (RCPilot1604) [inline src/main/java/tutorlink/storage/StudentStorage.java:48]: What happens if someone tampers with the storage file and stores a string in the percentageScore section?

**Review by RCPilot1604 — APPROVED** [review]
LTGM

File: src/main/java/tutorlink/storage/StudentStorage.java (hunk 1 above)
Comment (jinzihan2002) [reply src/main/java/tutorlink/storage/StudentStorage.java:48]: I removed the percentageScore section from studenlist.txt, instead it is calculated after loading all the storage files.
